### ISSUE TITLE
HomeFile Issues

### ISSUE THREAD

**Issue by HashanCP** [CodeRipperZ/DSA_Project#1]
we are writing all the objects in the list to a simple text file. check in the repository for text file format we are writing.
Since we do simple text i/o and 'ListHouse' class is NOT serailizable, please use the following classes:

java.io.File class - to refer to the file
java.util.Scanner class - to read from the file
java.io.PrintWriter class - to write to the file

save method will accept an array of 'ListHouse' objects
load method will load the data from the file and will return an array of 'ListHouse' object

take a look into these issues

**Comment by wsnperera** [comment]
i  updated that file according to these issues .pls check it.
